<?php
include_once "../metier/Adresse.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-01 at 14:26:54.
 */
class AdresseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Adresse
     */
    protected $objects;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->objects = new Adresse("4","rue de saint honoré","44000","Nantes");
        $this->objects->setId("3");
    }
    protected function tearDown() {
        
    }
    public function testGetId() {
        
           $this->assertEquals("3",$this->objects->getId());
    }

    public function testGetNumero() {
      $this->assertEquals("4",$this->objects->getNumero());
    }
    public function testGetRue() {
   
        $this->assertEquals("rue de saint honoré",$this->objects->getRue());
    }
    public function testGetCodePostal() {
       $this->assertEquals("44000",$this->objects->getCodePostal());
    }

    /**
     * @covers Adresse::getVille
     * @todo   Implement testGetVille().
     */
    public function testGetVille() {
      $this->assertEquals("Nantes",$this->objects->getVille());
    }

    /**
     * @covers Adresse::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        // Remove the following lines when you implement this test.
        $this->objects->setId("99");
          $this->assertEquals("99",$this->objects->getId());
    }

    /**
     * @covers Adresse::setNumero
     * @todo   Implement testSetNumero().
     */
    public function testSetNumero() {
       $this->objects->setNumero("39");
        $this->assertEquals("39",$this->objects->getNumero());
    }

    /**
     * @covers Adresse::setRue
     * @todo   Implement testSetRue().
     */
    public function testSetRue() {
        $this->objects->setRue("rue de nantes");
       $this->assertEquals("rue de nantes",$this->objects->getRue());
    }

    /**
     * @covers Adresse::setCodePostale
     * @todo   Implement testSetCodePostale().
     */
    public function testSetCodePostal() {
        $this->objects->setCodePostal("75000");
       $this->assertEquals("75000",$this->objects->getCodePostal());
    }

    /**
     * @covers Adresse::setVille
     * @todo   Implement testSetVille().
     */
    public function testSetVille() {
        $this->objects->setVille("Paris");
       $this->assertEquals("Paris",$this->objects->getVille());
    }

}
