<?php
include_once "../metier/Livre.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-06 at 13:54:40.
 */
class LivreTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Livre
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Livre("Les Miserables","Galimard","Livre Les Miserables","Victor Hugo");
   $this->object->setId("99");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Livre::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
          $this->assertEquals("99",$this->object->getId());
    }

    /**
     * @covers Livre::getTitre
     * @todo   Implement testGetTitre().
     */
    public function testGetTitre() {
        $this->assertEquals("Les Miserables",$this->object->getTitre());
    }

    /**
     * @covers Livre::getEdition
     * @todo   Implement testGetEdition().
     */
    public function testGetEdition() {
        // Remove the following lines when you implement this test.
     $this->assertEquals("Galimard",$this->object->getEdition());
    }

    /**
     * @covers Livre::getInformation
     * @todo   Implement testGetInformation().
     */
    public function testGetInformation() {
        // Remove the following lines when you implement this test.
        $this->assertEquals("Livre Les Miserables",$this->object->getInformation());
    }

    /**
     * @covers Livre::getAuteur
     * @todo   Implement testGetAuteur().
     */
    public function testGetAuteur() {
        $this->assertEquals("Victor Hugo",$this->object->getAuteur());
    }

    /**
     * @covers Livre::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
     $this->object->setId("49");
          $this->assertEquals("49",$this->object->getId());
    }

    /**
     * @covers Livre::setTitre
     * @todo   Implement testSetTitre().
     */
    public function testSetTitre() {
       $this->object->setTitre("test");
          $this->assertEquals("test",$this->object->getTitre());
    }

    /**
     * @covers Livre::setEdition
     * @todo   Implement testSetEdition().
     */
    public function testSetEdition() {
        // Remove the following lines when you implement this test.
        $this->object->setEdition("test edition");
          $this->assertEquals("test edition",$this->object->getEdition());
    }

    /**
     * @covers Livre::setInformation
     * @todo   Implement testSetInformation().
     */
    public function testSetInformation() {
         $this->object->setInformation("test information");
          $this->assertEquals("test information",$this->object->getInformation());
    }

    /**
     * @covers Livre::setAuteur
     * @todo   Implement testSetAuteur().
     */
    public function testSetAuteur() {
         $this->object->setAuteur("test auteur");
          $this->assertEquals("test auteur",$this->object->getAuteur());
    }

   

}
